### ISSUE TITLE
Features for development

### ISSUE THREAD

**Issue by Gilgalard** [Gilgalard/ZupBootcamp2020#1]
### Registration - Step #1
- [x] Data model
- [x] Service
- [x] Validator
- [x] Repository
- [x] Controller
- [x] Return code 201
- [x] Return code 400

### Registration - Step #2
- [x] Data model
- [x] Service
- [x] Validator
- [x] Check for step #1 registration data
- [x] Repository
- [x] Controller
- [x] Return code 201
- [x] Return code 400

### Registration - Step #3
- [x] Data model
  - [x] Image file on JSON through Base64
- [x] Validator
- [x] Service
- [x] Check for step #2 registration data
- [x] Repository (with file storage on database table)
- [x] Controller
- [x] Return code 201
- [x] Return code 400
- [x] Return code 404
- [x] Return code 422

### Registration - Step #4
- [x] Complete registration data's data model
  - [x] Image file on JSON through Base64
- [x] Validator
- [ ] Service
- [ ] Check for step #3 registration data
- [ ] Repository (with file storage on database table)
- [ ] Controller
- [ ] Return code 422

  #### New bank account
  - [ ] Account's data model
  - [ ] Service
  - [ ] Controller
  - [ ] Mock API simulating the third part API
    - [ ] Model
    - [ ] Service
    - [ ] Control
  - [ ] Service - Data approval/Refusal/Failure
  - [ ] Service - Generate fake account number
  - [ ] Repository
  - [ ] Return code 200

### First access
- [ ] Model
- [ ] Service
- [ ] Service - Token generation/Expiration control
- [ ] Service - Hash
- [ ] Repository
- [ ] Controller
- [ ] Return code 400
- [ ] Return code 200

### Money transfer
- [ ] Model
- [ ] Model for the recipient data
- [ ] Model for transfer schedule
- [ ] Service
- [ ] Validation
- [ ] External mock API for simulate another bank
- [ ] Authentication
- [ ] Return code 400
- [ ] Return code 200
